// <auto-generated />
namespace project_stack_overflow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ResolveQuestions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResolveQuestions));
        
        string IMigrationMetadata.Id
        {
            get { return "202110112136420_ResolveQuestions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
